### ISSUE TITLE
Any desire to open source the main firmware code?

### ISSUE THREAD

**Issue by mkaatman** [simap/pixelblaze#21]
I'd like to play around with it. If not, no worries.

**Comment by jvyduna** [comment]
Hi Matt,

No, not at the present time, sorry. 

Much of Pixelblaze is open source as shown in the README, but the core firmware is not. While we're proponents and beneficiaries of open source, after seeing what's happened to several similar projects, we believe the best way to ensure ongoing development and support is to keep this part closed source.

Pixelblaze proceeds mostly cover support and software development. Integrating the hardware and software is designed to minimize the problems people experience and also minimize the support costs around hardware, setup, and troubleshooting.

In selected cases we agree to commercial licensing agreements. Please email wizard@electromage.com if you'd like to ask about the options available.

To read a little more context, have a look at [this forum post](https://forum.electromage.com/t/pixelblaze-v2-v3-buy-software-license-without-hardware/887/6) from Wizard (Ben, the founder).

My personal take: The clone market is cutthroat, and Pixelblaze has been targeted before. I've been involved in some other open source / open hardware communities where the clones killed the otherwise promising company. Someday there might be a sustainable way to open-source the main firmware, and we'd be excited to get to that stage.
